# permissions for end users to view injectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: injector-viewer-role
rules:
- apiGroups:
  - injector.esparig.github.io
  resources:
  - injectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - injector.esparig.github.io
  resources:
  - injectors/status
  verbs:
  - get
